name: "Deploy to NuGet"

on: 
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'NumbersToWords/NumbersToWords.csproj'
  PACKAGE_OUTPUT_DIRECTORY: '${{ github.workspace }}/output1'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    
    - name: 'Run Tests'
      run: dotnet test
      
    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2
      
    - name: 'Print Version'
      run: echo "${{ steps.version.outputs.version-without-v }}"
      
    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -p:PackageVersion=${{ steps.version.outputs.version-without-v }}

    - name: 'Push package'
      run: dotnet nuget push '${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg' -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate
